CREATE DATABASE HQTCSDL
GO
USE HQTCSDL
GO

CREATE TABLE KHACHHANG (
	SDT VARCHAR(15) PRIMARY KEY,
    Ten NVARCHAR(100)
);
GO

CREATE TABLE KHACHHANGTHE (
	SDT VARCHAR(15) PRIMARY KEY,
	NgaySinh DATE,
    NgayLapThe DATE,
    LoaiThe NVARCHAR(50),
	FOREIGN KEY (SDT) REFERENCES KHACHHANG(SDT)
);
GO
CREATE TABLE PHIEUGIAMGIA (
    SDT VARCHAR(15),
	MaPhieu VARCHAR(15),
    TienGiamGia INT,
    NgayBatDau DATE,
    NgayKetThuc DATE,
    PRIMARY KEY (SDT, MaPhieu),
	FOREIGN KEY (SDT) REFERENCES KHACHHANGTHE(SDT)
);
GO

CREATE TABLE DANHMUC (
	IDDanhMuc VARCHAR(15),
	TenDanhMuc NVARCHAR(50),
	PRIMARY KEY (IDDanhMuc)
);
GO

CREATE TABLE SANPHAM (
    IDSanPham VARCHAR(15) PRIMARY KEY,
	TenSanPham NVARCHAR(50),
    NSX NVARCHAR(100),
    GiaNiemYet INT,
	IDDanhMuc VARCHAR(15),
	FOREIGN KEY (IDDanhMuc) REFERENCES DANHMUC(IDDanhMuc)
);
GO



CREATE TABLE GIAMGIA (
    MaGiamGia VARCHAR(15) PRIMARY KEY,
    TiLeGiamGia INT,
    NgayBatDauGiam DATE,
    NgayKetThucGiam DATE,
    SoLuongGiam INT,
	TrangThaiSale BIT
);
GO

CREATE TABLE FlashSale (
    MaGiamGia VARCHAR(15),
    IDSanPham VARCHAR(15),
    PRIMARY KEY (MaGiamGia),
    FOREIGN KEY (MaGiamGia) REFERENCES GIAMGIA(MaGiamGia),
    FOREIGN KEY (IDSanPham) REFERENCES SANPHAM(IDSanPham)
);
GO

CREATE TABLE ComboSale (
    MaGiamGia VARCHAR(15),
    IDSanPham1 VARCHAR(15),
	IDSanPham2 VARCHAR(15),
    PRIMARY KEY (MaGiamGia),
    FOREIGN KEY (MaGiamGia) REFERENCES GIAMGIA(MaGiamGia),
    FOREIGN KEY (IDSanPham1) REFERENCES SANPHAM(IDSanPham),
	FOREIGN KEY (IDSanPham1) REFERENCES SANPHAM(IDSanPham)
);
GO

CREATE TABLE MemberSale (
    MaGiamGia VARCHAR(15),
    IDSanPham VARCHAR(15),
    LoaiKH VARCHAR(50),
    PRIMARY KEY (MaGiamGia),
    FOREIGN KEY (MaGiamGia) REFERENCES GIAMGIA(MaGiamGia),
    FOREIGN KEY (IDSanPham) REFERENCES SANPHAM(IDSanPham)
);
GO

CREATE TABLE DonHang (
	MaDonHang VARCHAR(15),
	SDT VARCHAR(15),
    NgayBan DATE,
    TongGiaTriDonHang BIGINT,
	CachThanhToan NVARCHAR(50),
	TinhTrangDonHang NVARCHAR(50),
	DonHangType NVARCHAR(15),
	DiaChiGiaoHang NVARCHAR(50),
	TinhTrangGiaoHang NVARCHAR(50),
	PRIMARY KEY (MaDonHang),
	FOREIGN KEY (SDT) REFERENCES KHACHHANG(SDT)
);
GO

CREATE TABLE SanPhamDonHang (
    MaDonHang VARCHAR(15),
    IDSanPham VARCHAR(15),
    SoLuong INT,
    PRIMARY KEY (MaDonHang, IDSanPham),
    FOREIGN KEY (IDSanPham) REFERENCES SANPHAM(IDSanPham),
	FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaDonHang)
);
GO

CREATE TABLE KhoHang (
    IDSanPham VARCHAR(15),
    SL_SP_TD INT,
	SL_HT INT,
	SL_CG INT,
    PRIMARY KEY (IDSanPham),
    FOREIGN KEY (IDSanPham) REFERENCES SANPHAM(IDSanPham)
);
GO

CREATE TABLE PhieuDat (
    MaPhieuDat VARCHAR(15) PRIMARY KEY,
    NgayDat DATE
);
GO

CREATE TABLE HangDat (
    MaPhieuDat VARCHAR(15),
    IDSanPham VARCHAR(15),
    SLDat INT,
    SLDaGiao INT,
    PRIMARY KEY (MaPhieuDat, IDSanPham),
    FOREIGN KEY (MaPhieuDat) REFERENCES PhieuDat(MaPhieuDat),
    FOREIGN KEY (IDSanPham) REFERENCES SANPHAM(IDSanPham)
);
GO